trigger: none

pool:
  vmImage: windows-2019

steps:
- powershell: |
    $PSVersionTable

    $baseDirectory = Get-Location

    $targetFrameworks = @("netstandard2.0", "net6.0")

    $targetFrameworks | ForEach-Object {
      # Define what each job does
      $scriptBlock = {
        param($framework, $baseDirectory)

        # Example using ipconfig to get network information
        $command = "ipconfig /all" 
        $ipConfigOutput = & Invoke-Expression $command

        # Hypothetical: Store output with framework identifier for clarity
        $outputPath = Join-Path $baseDirectory "ipconfig_$framework.txt"
        $ipConfigOutput | Out-File $outputPath 
      }

      # Execute the jobs in parallel
      Start-Job $scriptBlock -ArgumentList $_, $baseDirectory
    }
    
    Write-Host "Start network diagnostics on all frameworks in parallel..."

    Get-Job | Wait-Job

    Get-Job | Receive-Job

    Get-Job | Remove-Job

    Write-Host "Invoke all jobs successfully."
